name: huk_coding_challenge
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython=8.7.0
  - notebook=6.5.2
  - jupyterlab=3.5.2
  - pandas=1.5.2
  - pandas-profiling=3.6.2
  - numpy=1.23.5
  - scikit-learn=1.2.0
  - pip=22.3.1
  - pip:
      - autopep8==2.0.0
      - pylint==2.15.8
      - imblearn==0.0